# To run locally
# npx @techdocs/cli serve -v -c ./mkdocs.yml
# 
site_name: 'synthetic-monitoring-api-go-client Internal Documentation'
repo_url: https://github.com/grafana/synthetic-monitoring-api-go-client
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.sections

plugins:
  - techdocs-core
