---
kind: pipeline
name: build
steps:
- commands:
  - echo $DRONE_RUNNER_NAME
  image: alpine
  name: runner identification
- commands:
  - make deps
  - ./scripts/enforce-clean
  image: ghcr.io/grafana/grafana-build-tools:v0.4.1
  name: deps
- commands:
  - make lint
  image: ghcr.io/grafana/grafana-build-tools:v0.4.1
  name: lint
- commands:
  - make test
  image: ghcr.io/grafana/grafana-build-tools:v0.4.1
  name: test
- commands:
  - git fetch origin --tags
  - git status --porcelain --untracked-files=no
  - git diff --no-ext-diff --quiet
  - ./scripts/version
  - make build
  image: ghcr.io/grafana/grafana-build-tools:v0.4.1
  name: build
trigger:
  ref:
  - refs/heads/main
  - refs/pull/**
  - refs/tags/v*.*.*
type: docker
---
kind: signature
hmac: 867051d28a15bc3dcfd3b7acb5af7db26afb724985d4fa3818bd8a1fc2a0d152

...
