---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: runner identification
  image: alpine
  commands:
  - echo $DRONE_RUNNER_NAME

- name: lint
  image: golang:1.17
  commands:
  - make lint

- name: test
  image: golang:1.17
  commands:
  - make test

- name: build
  image: golang:1.17
  commands:
  - git fetch origin --tags
  - git status --porcelain --untracked-files=no
  - git diff --no-ext-diff --quiet
  - ./scripts/version
  - make build

trigger:
  ref:
  - refs/heads/main
  - refs/pull/**
  - refs/tags/v*.*.*

---
kind: signature
hmac: e634ab72aba3229c8ce2e31eeabf3f64ddb8b6a1b7fc85ceca64a8c58ab172a8

...
