name: Publish TechDocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - '.github/workflows/publish-techdocs.yaml'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
permissions: {}
jobs:
  publish-docs:
    uses: grafana/shared-workflows/.github/workflows/publish-techdocs.yaml@2f1ddaf3ce1aa677356243d0dd584be33cfa35e3 # main
    permissions:
      contents: read
      id-token: write
    with:
      namespace: default
      kind: component
      name: synthetic-monitoring-api-go-client
      default-working-directory: .
