name: Validate renovate config
on:
  pull_request:
    paths:
      # When renovate config changes:
      - "renovate.*"
      - ".renovate.*"
      - ".github/renovate.*"

permissions:
  contents: none

jobs:
  renovate:
    permissions:
      # Needed for logging into vault.
      contents: read
      id-token: write
    runs-on: ubuntu-amd64-small
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check drift
        run: |
          ./scripts/generate-renovate-config

          ./scripts/check-renovate-config "$GITHUB_STEP_SUMMARY"

      - name: Validate Renovate Config
        uses: grafana/shared-workflows/actions/validate-renovate-config@b7474485d59e97b4ee81d5f94f442f072380bf79 # validate-renovate-config/v0.1.4
        with:
          path: .github/renovate.json
